{% set name = "des-sxdes" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/esheldon/sxdes/archive/{{ version }}.tar.gz
  sha256: 73a00681acca558d13c5c67baa2e604db354f7770f3538494b91941c43592b53

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - sep

test:
  imports:
    - sxdes

about:
  home: https://github.com/esheldon/sxdes
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Run the sep code with DES settings

extra:
  recipe-maintainers:
    - beckermr
