{% set name = "des-sxdes" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/esheldon/sxdes/archive/{{ version }}.tar.gz
  sha256: d6efcbc1b34af662742fa348dc177e11f5beec0d1482fd8d98905ac284218e43

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - sep

test:
  requires:
    - python {{ python_min }}
  imports:
    - sxdes

about:
  home: https://github.com/esheldon/sxdes
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Run the sep code with DES settings

extra:
  recipe-maintainers:
    - beckermr
